### ISSUE TITLE
Relationship with Codehaus Mojo xml-maven-plugin (is it a fork or replacement ?)

### ISSUE THREAD

**Issue by draco31fr** [openjax/xml#11]
Hello,

The name `xml-maven-plugin` is already used by [CodeHaus Mojo](http://www.mojohaus.org/xml-maven-plugin/).

- Is this a [fork of CodeHaus](https://github.com/mojohaus/xml-maven-plugin) ?
- Is your version a drop-in replacement for this plugin ?

If your work has no commitment with CodeHaus initiative, I suggest you add a notice about the (unexpected) artifact's name equality.

Whatever you motivation, thanks you for your work and the choice of the MIT licencing.

Regards

**Comment by safris** [comment]
Hi @draco31fr, apologies for the tardy response. To answer your questions:
* This mojo is **not** a fork of [`xml-maven-plugin` from CodeHaus](http://www.mojohaus.org/xml-maven-plugin/).
* It is not a drop-in replacement.

I have [added a note in the README.md regarding this point](https://github.com/openjax/xml/commit/d33e94b735f0950dcd572f6f007e295819553bdb).

**Comment by draco31fr** [comment]
Hello
Thanks for clarification !
