### ISSUE TITLE
Null pointer exception when validating XML with no targetNamespace defined in XSD

### ISSUE THREAD

**Issue by nsuitter** [openjax/xml#7]
Hi @safris,

First of all, I love your work on this!

One question though: I'm running into a null pointer exception when validating an XML with a global namespace. Have you ever run into this and how should I proceed?

This is the line that the error is pointing to:
https://github.com/openjax/xml/blob/2d173535cd3e566fc7bde39c5b0b0b8ea405f2d3/sax/src/main/java/org/openjax/xml/sax/Validator.java#L325

Please let me know if you need any other information!

**Comment by nsuitter** [comment]
Fleshing out this issue... looks like this is actually an error when validating the xsd. When there is no targetNamespace specified in the schema, I get a null pointer exception.

**Comment by safris** [comment]
Hi @nsuitter, thanks for the message. Can you provide an example XSD to reproduce this problem?

**Comment by safris** [comment]
Hi @nsuitter, I have checked in [a commit](https://github.com/openjax/xml/commit/54e1e3e3b3c2da86adf09c703be9ac529f5941de) that should fix the issue you experienced. A new build of `org.openjax:xml:0.9.5-SNAPSHOT` has been deployed to the Sonatype snapshot repo. I will close this issue, but please reopen if you continue to experience it.
